### ISSUE TITLE
When called via ansible-playbook with "--diff" flag, throws an error

### ISSUE THREAD

**Issue by rfrush** [koichirok/ansible-module-authconfig#2]
If I use the -D (--diff) option on ansible playbook, this module throws an error.  I really don't know enough about ansible internals to suggest where to look, but it appears that the -D options is looking for 'results' that this module does not implement.

When called with only --check,  module operates as expected.

ERROR message:

fatal: [isxxt001.is.colostate.edu]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to isxxt001.is.colostate.edu closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_kZughG/ansible_module_authconfig.py\", line 825, in <module>\r\n    main()\r\n  File \"/tmp/ansible_kZughG/ansible_module_authconfig.py\", line 806, in main\r\n    'after': out}\r\nNameError: global name 'result' is not defined\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

**Comment by koichirok** [comment]
which version of ansible are you using?

**Comment by rfrush** [comment]
We're running 2.4.0, though 2.4.2 is staged for our next upgrade cycle.

```
# ansible --version
ansible 2.4.0.0
  config file = .../ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 08:36:59) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

**Comment by koichirok** [comment]
Hi,

I fixed this error and fixed version can be downloaded from galaxy.
Please test it.

**Comment by rfrush** [comment]
A simple test (running with --check --diff) passed with no errors.    Thanks for digging into this!
