### ISSUE TITLE
Getting NameError: name 'Authconfig' is not defined error when running playbook with this module

### ISSUE THREAD

**Issue by re-schneider** [koichirok/ansible-module-authconfig#3]
Hi,

I found you module and followed the documentation to use it:
* installed it on my control host with ansible-galaxy
* added the role declaration at the top of the playbook: 
  roles:
    - koichirok.authconfig-module
* Added a task using it in the same playbook:
  authconfig:
    enablemkhomedir: yes
    enablesssdauth: yes

Unfortunately, running the playbook against a RHEL 7 machine fails on this task with the "NameError: name 'Authconfig' is not defined" error.

The worst part is that I double-checked and the authconfig package is installed and the /usr/share/authconfig/authconfig.py file exists on the system but weirdly it seems like the sys.path is not doing what it is supposed to do.

FYI, the control host is running ansible 2.10.5.

I am opening an issue here as (as usual) nothing in the Ansible documentation not quick web search yields anything useful to assist with such debugging and I am not yet familiar enough with Ansible deep-gut debugging to track it down to where it fails (I have run with -vvv + ANSIBLE_KEEP_REMOTE_FILES=1 and was able to have the AnsiballZ and running it manually on the target RHEL 7 host yield the same error (local python is 2.7.5) yet the authconfig from your module is part of the AnsiballZ and the sys.path should resolve properly short of a weird ansible trick that would prevent proper exec or proper context for the exec).

Thank in advance to whoever has the dark magic to point to a possible way to bring this back on track (as it is a convenient module).

**Comment by bschonec** [comment]
I'm experiencing the same issue.  Did you get any resolution to the problem?

**Comment by re-schneider** [comment]
Unfortunately no.
In the meantime, the scope of the playbook I was writing changed and the LDAP config got descoped so I was happy to drop the manual version of what this module provides.

Hopefully somebody will figure out the problem (maybe simple as a wrong config or more serious as something must be updated to play well with a recent Ansible version).

**Comment by koichirok** [comment]
sorry for long delay, I fixed this issue and update galaxy.

please test it.
